#!/bin/sh

# Start the gamepad provider
gamepad &

# Start the audio provider
audio &

# Start the display provider
display &

# Be crash resistant
while true
do
	if [ -f /tmp/command ]
	then
		# Move the command (so we don't risk getting deadlocked by crashing processes)
		mv /tmp/command /tmp/current_command

		# Execute the command
		/bin/sh /tmp/current_command
	else
		# Start GarlicUI
		garlicui
	fi
done
