#ifndef GAMEPAD_H
#define GAMEPAD_H

#include <stdint.h>

// The button states
#define BTN_RELEASED 0
#define BTN_PRESSED 1
#define BTN_REPEAT 2

// System buttons
#define MERGED_SCANCODE_VOLUME_MINUS BTN_C
#define MERGED_SCANCODE_VOLUME_PLUS BTN_Z
#define MERGED_SCANCODE_POWER BTN_TOP

// XBOX360 gamepad buttons
#define MERGED_SCANCODE_HOME BTN_MODE
#define MERGED_SCANCODE_A BTN_SOUTH
#define MERGED_SCANCODE_B BTN_EAST
#define MERGED_SCANCODE_X BTN_WEST
#define MERGED_SCANCODE_Y BTN_NORTH
#define MERGED_SCANCODE_L1 BTN_TL
#define MERGED_SCANCODE_R1 BTN_TR
#define MERGED_SCANCODE_SELECT BTN_SELECT
#define MERGED_SCANCODE_START BTN_START
#define MERGED_SCANCODE_L3 BTN_THUMBL
#define MERGED_SCANCODE_R3 BTN_THUMBR

// XBOX360 gamepad axis
#define MERGED_AXIS_LEFT_ANALOG_HORIZONTAL 0
#define MERGED_AXIS_LEFT_ANALOG_VERTICAL 1
#define MERGED_AXIS_LEFT_TRIGGER 2
#define MERGED_AXIS_RIGHT_ANALOG_HORIZONTAL 3
#define MERGED_AXIS_RIGHT_ANALOG_VERTICAL 4
#define MERGED_AXIS_RIGHT_TRIGGER 5
#define MERGED_AXIS_DPAD_HORIZONTAL 16
#define MERGED_AXIS_DPAD_VERTICAL 17

// Analog stick axis range, fuzz and flat values
#define MERGED_ANALOG_VALUE_MIN -32767
#define MERGED_ANALOG_VALUE_MAX 32768
#define MERGED_ANALOG_VALUE_FUZZ 64
#define MERGED_ANALOG_VALUE_FLAT 4096

// Dpad axis range, fuzz and flat values
#define MERGED_DPAD_VALUE_MIN -1
#define MERGED_DPAD_VALUE_MAX 1
#define MERGED_DPAD_VALUE_FUZZ 0
#define MERGED_DPAD_VALUE_FLAT 0

// Trigger axis range, fuzz and flat values
#define MERGED_TRIGGER_VALUE_MIN 0
#define MERGED_TRIGGER_VALUE_MAX 255
#define MERGED_TRIGGER_VALUE_FUZZ 0
#define MERGED_TRIGGER_VALUE_FLAT 0

int32_t get_merged_axis_min_value(int axis);
int32_t get_merged_axis_max_value(int axis);

void hotkey(struct input_event * ev);

#endif
