#ifndef RG35XXPLUS_H
#define RG35XXPLUS_H

// The input device paths
#define RG35XXPLUS_PMU_KEYS "/dev/input/event0"
#define RG35XXPLUS_GAMEPAD "/dev/input/event1"

// System buttons (axp2202-pek)
#define RG35XXPLUS_SCANCODE_VOLUME_MINUS KEY_VOLUMEDOWN
#define RG35XXPLUS_SCANCODE_VOLUME_PLUS KEY_VOLUMEUP
#define RG35XXPLUS_SCANCODE_POWER KEY_POWER

// XBOX360 gamepad buttons (Deeplay-keys)
#define RG35XXPLUS_SCANCODE_HOME BTN_TL2
#define RG35XXPLUS_SCANCODE_A BTN_SOUTH
#define RG35XXPLUS_SCANCODE_B BTN_EAST
#define RG35XXPLUS_SCANCODE_X BTN_NORTH
#define RG35XXPLUS_SCANCODE_Y BTN_C
#define RG35XXPLUS_SCANCODE_L1 BTN_WEST
#define RG35XXPLUS_SCANCODE_R1 BTN_Z
#define RG35XXPLUS_SCANCODE_L2 BTN_SELECT
#define RG35XXPLUS_SCANCODE_R2 BTN_START
#define RG35XXPLUS_SCANCODE_SELECT BTN_TL
#define RG35XXPLUS_SCANCODE_START BTN_TR
#define RG35XXPLUS_SCANCODE_DPAD_UP KEY_UP
#define RG35XXPLUS_SCANCODE_DPAD_LEFT KEY_LEFT
#define RG35XXPLUS_SCANCODE_DPAD_RIGHT KEY_RIGHT
#define RG35XXPLUS_SCANCODE_DPAD_DOWN KEY_DOWN

void merge_rg35xxplus_inputs(int merged_gamepad);

#endif